### PR TITLE
ENH: Add ARM builds and notebook test

### PR DESCRIPTION
**Pull request by tbirdso**
Applies recent changes in ITKRemoteModuleBuildTestPackageAction to add Jupyter Notebook tests to CI.

Includes fix for `itk.SplitComponentsImageFilter` wrapping where the number of components to split for RGB/RGBA images was tied to the image dimension rather than the implied pixel dimension.

### CODE REVIEW

**Comment by tbirdso** [comment]
@thewtex Glancing back through [`ITKSplitComponents.ipynb`](https://github.com/InsightSoftwareConsortium/ITKSplitComponents/blob/master/examples/ITKSplitComponents.ipynb) notebook errors in my local Linux installation with `itkwidgets==1.0a21`, the example made use of `ipywidgets` components such as `HBox`, `VBox`, and `interactive`. Are these supported in `itkwidgets>=1.0a21`? Is there a better way to visualize scrolling through distinct image channels?

EDIT: Initial test run here uses `itkwidgets==0.32.5` and seems to fail at first `view`: https://github.com/tbirdso/ITKSplitComponents/actions/runs/3850782393

**Comment by thewtex** [comment]
ipywidget support in 1.0 is in progress (tracked in https://github.com/InsightSoftwareConsortium/itkwidgets/issues/556). 

> FAILED examples/ITKSplitComponents.ipynb:: - TraitError: label_image_weights shape expected to have 1 components, but got () components

This should have been addressed with 0.32.5 re: https://github.com/InsightSoftwareConsortium/itkwidgets/issues/588

Care may need to be taken in how jupyter / itkwidgets is installed to ensure traitlets is < 5.7?

**Comment by tbirdso** [comment]
It does look like traitlets 5.8 is installed, will update `requirements.txt`. From the log:

```
Downloading traitlets-5.8.0-py3-none-any.whl
```

**Comment by tbirdso** [comment]
Downgrading to `traitlets<5.7.0` in `requirements.txt` resolved the issue 👍

https://github.com/InsightSoftwareConsortium/ITKSplitComponents/actions/runs/3858346527/jobs/6576762362

Rebased and ready for review.

**Review by dzenanz — APPROVED** [review]
Looks good on a glance.

**Pull request merged**
