### PR TITLE
ENH: Bump to ITK v5.3rc04.post3

### PR DESCRIPTION
**Pull request by tbirdso**

### CODE REVIEW

**Review by dzenanz — COMMENTED** [review]
Are CI failures expected?

**Comment by tbirdso** [comment]
Not expected. I see v5.3rc04.post3 builds at https://github.com/InsightSoftwareConsortium/ITKPythonBuilds/releases/tag/v5.3rc04.post3 as expected but it seems like the archive is not extracted properly after download? Will need to investigate.

**Comment by tbirdso** [comment]
CI is now passing 🟢

**Review by dzenanz — APPROVED** [review]

**Comment by dzenanz** [comment]
Will this recipe fix https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/issues/133? If so, that will allow getting https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/pull/134 through, so I can get it off my mind.

**Comment by tbirdso** [comment]
@dzenanz I will follow up in that issue. I am not sure that the failure in #134 is the exact same cause as it looks like it is failing to find gcc. Let's implement the ITK bump and follow up from there.

**Pull request merged**
